// ****************************************************************
// NOT CLEAR YET HOW IT IS GOING TO BE IMLEMENTED
// ****************************************************************
// BOOKING CAN ONLY BE DELETED BY ADMIN OR IF ALL CUSTOMERS CANCELLED IT
// FIND BOOKING
// CHECK IF IT IS VALID
// FIND RESPECTIVE CUSTOMERS
// CHECK IF CUSTOMER IS SAME AS PROVIDED IN THE BOOKING
// CHECK IF IT IS VALID AND IT BELONGS TO THE BOOKING
// FIND CAR FROM BOOKING
// CHECK IF IT IS VALID
// CHECK CAR IN THE DATABASE AND IT BELONGS TO THE BOOKING
// -------------------DELETE PROCESS-----------------------
// GO TO
